---
include:
  # Scanner Pocket - Sharp Memory LCD (LS013B7DH05)
  - board: xiao_ble/nrf52840
    shield: scanner_pocket
    artifact-name: scanner_pocket

  # Settings reset utility
  - board: xiao_ble/nrf52840
    shield: settings_reset
